local orig_devushka_quest_one_reward = xr_effects.devushka_quest_one_reward

xr_effects.devushka_quest_one_reward = function(first_speaker, second_speaker)
    alife_create_item("nomad_outfit", db.actor)
    alife_create_item("wpn_knife3"  , db.actor)
    alife_create_item("kit_hunt"    , db.actor)
    news_manager.relocate_item(db.actor, "in", "nomad_outfit", 1)
    news_manager.relocate_item(db.actor, "in", "wpn_knife3"  , 1)
    news_manager.relocate_item(db.actor, "in", "kit_hunt"    , 1)
end