------------------------------------------------------------------------------
--                      Пропавший отряд                           --
------------------------------------------------------------------------------

function xr_effects.dl_tech_unlocked_pda_vorona()
	local snd = sound_object([[characters_voice\scenario\deadlake\dl_tech_unlocked_pda_vorona]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
	SendTip("wiz_message_1", "wiz_pianist", nil, 25, "ui_iconsTotal_grouping")
end

function xr_effects.foma_reward_give_treasure()
	local snd = sound_object([[characters_voice\scenario\way_in_zone\foma\wiz_foma_good_job_reward]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
	SendTip("wiz_message_2", "wiz_foma", nil, 25, "ui_iconsTotal_grouping")
end

function xr_effects.dl_message_00()
	local snd = sound_object([[characters_voice\scenario\deadlake\actor\dl_message_00]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
	SendTip("wiz_message_3", "wiz_zmey", nil, 25, "ui_iconsTotal_grouping")
end

function xr_effects.dl_message_01()
	local snd = sound_object([[characters_voice\scenario\deadlake\dl_message_01]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
	SendTip("wiz_message_4", "wiz_krasnopolsky", nil, 25, "ui_iconsTotal_grouping")
end
function xr_effects.dl_message_02()
	local snd = sound_object([[characters_voice\scenario\deadlake\actor\dl_message_02]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
	SendTip("wiz_message_5", "wiz_zmey", nil, 25, "ui_iconsTotal_grouping")
end

function xr_effects.dl_message_03()
	local snd = sound_object([[characters_voice\scenario\deadlake\dl_message_03]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
	SendTip("wiz_message_6", "wiz_krasnopolsky", nil, 25, "ui_iconsTotal_grouping")
end
function xr_effects.dl_message_04()
	local snd = sound_object([[characters_voice\scenario\deadlake\actor\dl_message_04]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
	SendTip("wiz_message_7", "wiz_zmey", nil, 25, "ui_iconsTotal_grouping")
end

function xr_effects.dl_message_05()
	local snd = sound_object([[characters_voice\scenario\deadlake\dl_message_05]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
	SendTip("wiz_message_8", "wiz_krasnopolsky", nil, 25, "ui_iconsTotal_grouping")
end
function xr_effects.dl_message_06()
	local snd = sound_object([[characters_voice\scenario\deadlake\actor\dl_message_06]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
	SendTip("wiz_message_9", "wiz_zmey", nil, 25, "ui_iconsTotal_grouping")
end

function xr_effects.bolotnaya_tvar_die_actor()
	local snd = sound_object([[characters_voice\scenario\way_in_zone\actor\wiz_actor_message_to_foma]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
	SendTip("wiz_message_10", "wiz_zmey", nil, 25, "ui_iconsTotal_grouping")
end

function xr_effects.bolotnaya_tvar_die_foma()
	local snd = sound_object([[characters_voice\scenario\way_in_zone\foma\wiz_foma_good_i_give_info]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
	SendTip("wiz_message_11", "wiz_foma", nil, 25, "ui_iconsTotal_grouping")
end

function xr_effects.katacombs_foma_message()
	local snd = sound_object([[characters_voice\scenario\way_in_zone\foma\wiz_foma_i_have_news]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
	SendTip("wiz_message_12", "wiz_foma", nil, 25, "ui_iconsTotal_grouping")
end

function xr_effects.uninvited_guests_message_01()
	local snd = sound_object([[characters_voice\scenario\way_in_zone\merc\wiz_merc_fraze_talk_1]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
	SendTip("wiz_message_13", "wiz_mercs", nil, 25, "ui_inGame2_Hmuriy")
end

function xr_effects.uninvited_guests_message_02()
	local snd = sound_object([[characters_voice\scenario\way_in_zone\merc\wiz_merc_fraze_talk_3]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
	SendTip("wiz_message_14", "wiz_mercs", nil, 25, "ui_inGame2_Grif")
end

function xr_effects.uninvited_guests_message_03()
	local snd = sound_object([[characters_voice\scenario\way_in_zone\merc\wiz_merc_fraze_talk_2]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
	SendTip("wiz_message_15", "wiz_mercs", nil, 25, "ui_inGame2_Hmuriy")
end

function xr_effects.ivanich_unlock_signal_message()
	local snd = sound_object([[characters_voice\radio\way_in_zone\wiz_ivanich_pda_unlocked]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
	SendTip("wiz_message_16", "wiz_ivanych", nil, 25, "ui_inGame2_Istoriya_dolga")
end

function xr_effects.zametki_pda_poslannika_1()
	local snd = sound_object([[characters_voice\scenario\way_in_zone\merc\wiz_pda_poslannika_krivogo_1]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.zametki_pda_poslannika_2()
	local snd = sound_object([[characters_voice\scenario\way_in_zone\merc\wiz_pda_poslannika_krivogo_2]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.zametki_pda_poslannika_3()
	local snd = sound_object([[characters_voice\scenario\way_in_zone\merc\wiz_pda_poslannika_krivogo_3]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.codes_messages_kosta_to_mercs()
	SendTip("wiz_message_17", "wiz_neutral", nil, 25, "ui_inGame2_PD_Drug_Stalkerov")
end

function xr_effects.codes_messages_mercs_to_kosta()
	SendTip("wiz_message_18", "wiz_mercs", nil, 25, "ui_inGame2_Killers")
end

function xr_effects.rjaviu_first_message()
	local snd = sound_object([[characters_voice\radio\way_in_zone\wiz_stalker_rjaviu_est_delo_podoidi]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
	SendTip("wiz_message_19", "wiz_rusty", nil, 25, "ui_inGame2_Vano")
end

function xr_effects.dl_voron_notes()
	local snd = sound_object([[characters_voice\scenario\deadlake\dl_voron_notes]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.dl_grek_notes()
	local snd = sound_object([[characters_voice\scenario\deadlake\dl_grek_notes]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.zametki_pda_nazara_1()
	local snd = sound_object([[characters_voice\radio\way_in_zone\wiz_zametki_pda_nazara_1]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.zametki_pda_nazara_2()
	local snd = sound_object([[characters_voice\radio\way_in_zone\wiz_zametki_pda_nazara_2]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.zametki_pda_nazara_3()
	local snd = sound_object([[characters_voice\radio\way_in_zone\wiz_zametki_pda_nazara_3]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.rjaviu_molis_tvar()
	local snd = sound_object([[characters_voice\radio\way_in_zone\wiz_stalker_rjaviu_molis_tvar]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.gonec_pravosudiya_rjaviu_message()
	local snd = sound_object([[characters_voice\radio\way_in_zone\wiz_stalker_rjaviu_zmey_podoydi]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
	SendTip("Змей, подойди.", "wiz_rusty", nil, 25, "ui_inGame2_Vano")
end

function xr_effects.new_writes_in_diary()
	SendTip("Новая запись в дневнике.", "wiz_informator", nil, 25, "ui_inGame2_PD_Drug_Stalkerov")
end

function xr_effects.dl_sos_message()
	local snd = sound_object([[characters_voice\scenario\deadlake\dl_sos_message]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
	SendTip("wiz_message_20", "wiz_toha", nil, 25, "ui_inGame2_Noy")
end

-------------- Тёмная Долина alife frazes .---------------

function xr_effects.val_alife_counter_attack_check_1()
	local snd = sound_object([[characters_voice\scenario\alife_words\check_1]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
	SendTip("wiz_message_21", "wiz_free_stalkers", nil, 25, "ui_inGame2_neutral_2")
end

function xr_effects.val_alife_counter_attack_check_2()
	local snd = sound_object([[characters_voice\scenario\alife_words\check_2]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
	SendTip("wiz_message_22", "wiz_free_stalkers", nil, 25, "ui_inGame2_neutral_2")
end

function xr_effects.val_alife_counter_attack_check_3()
	local snd = sound_object([[characters_voice\scenario\alife_words\check_3]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
	SendTip("wiz_message_23", "wiz_free_stalkers", nil, 25, "ui_inGame2_neutral_2")
end

function xr_effects.val_alife_counter_attack_check_4()
	local snd = sound_object([[characters_voice\scenario\alife_words\check_4]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
	SendTip("wiz_message_24", "wiz_free_stalkers", nil, 25, "ui_inGame2_neutral_2")
end

function xr_effects.val_alife_counter_attack_counter_attack_begin_1()
	local snd = sound_object([[characters_voice\scenario\alife_words\counter_attack_begin_1]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
	SendTip("wiz_message_25", "wiz_free_stalkers", nil, 25, "ui_inGame2_neutral_2")
end

function xr_effects.val_alife_counter_attack_counter_attack_begin_2()
	local snd = sound_object([[characters_voice\scenario\alife_words\counter_attack_begin_2]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
	SendTip("wiz_message_26", "wiz_free_stalkers", nil, 25, "ui_inGame2_neutral_2")
end

function xr_effects.val_alife_counter_attack_counter_attack_begin_3()
	local snd = sound_object([[characters_voice\scenario\alife_words\counter_attack_begin_3]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
	SendTip("wiz_message_27", "wiz_free_stalkers", nil, 25, "ui_inGame2_neutral_2")
end

function xr_effects.val_alife_counter_attack_reply_1()
	local snd = sound_object([[characters_voice\scenario\alife_words\reply_1]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
	SendTip("wiz_message_28", "wiz_free_stalkers", nil, 25, "ui_inGame2_neutral_2")
end

function xr_effects.val_alife_counter_attack_reply_2()
	local snd = sound_object([[characters_voice\scenario\alife_words\reply_2]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
	SendTip("wiz_message_29", "wiz_free_stalkers", nil, 25, "ui_inGame2_neutral_2")
end


function xr_effects.wiz_pda_rezaka_info()
	local snd = sound_object([[characters_voice\scenario\way_in_zone\wiz_pda_rezaka_info_new]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end


-------------- Мысли Главного героя.---------------

function xr_effects.hero_thoughts_01()
	local snd = sound_object([[characters_voice\scenario\way_in_zone\actor\hero_thoughts_phase_1]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_02()
	local snd = sound_object([[characters_voice\scenario\way_in_zone\actor\hero_thoughts_phase_2]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_03()
	local snd = sound_object([[characters_voice\scenario\way_in_zone\actor\hero_thoughts_phase_3]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_04()
	local snd = sound_object([[characters_voice\scenario\way_in_zone\actor\hero_thoughts_phase_4]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_05()
	local snd = sound_object([[characters_voice\scenario\way_in_zone\actor\hero_thoughts_phase_5]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_06()
	local snd = sound_object([[characters_voice\scenario\way_in_zone\actor\hero_thoughts_phase_6]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_07()
	local snd = sound_object([[characters_voice\scenario\way_in_zone\actor\hero_thoughts_phase_7]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_08()
	local snd = sound_object([[characters_voice\scenario\way_in_zone\actor\hero_thoughts_phase_8]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_09()
	local snd = sound_object([[characters_voice\scenario\way_in_zone\actor\hero_thoughts_phase_9]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_10()
	local snd = sound_object([[characters_voice\scenario\way_in_zone\actor\hero_thoughts_phase_10]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_11()
	local snd = sound_object([[characters_voice\scenario\way_in_zone\actor\hero_thoughts_phase_11]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_12()
	local snd = sound_object([[characters_voice\scenario\way_in_zone\actor\hero_thoughts_phase_12]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_13()
	local snd = sound_object([[characters_voice\scenario\way_in_zone\actor\hero_thoughts_phase_13]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_14()
	local snd = sound_object([[characters_voice\scenario\way_in_zone\actor\hero_thoughts_phase_14]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_15()
	local snd = sound_object([[characters_voice\scenario\way_in_zone\actor\hero_thoughts_phase_15]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_16()
	local snd = sound_object([[characters_voice\scenario\way_in_zone\actor\hero_thoughts_phase_16]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_17()
	local snd = sound_object([[characters_voice\scenario\way_in_zone\actor\hero_thoughts_phase_17]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_17_1()
	local snd = sound_object([[characters_voice\scenario\way_in_zone\actor\hero_thoughts_phase_17_1]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

-------------- Вторая глава - Мысли Главного Героя.---------------

function xr_effects.hero_thoughts_18()
	local snd = sound_object([[characters_voice\scenario\deadlake\actor\hero_thoughts_phase_18]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_19()
	local snd = sound_object([[characters_voice\scenario\deadlake\actor\hero_thoughts_phase_19]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_20()
	local snd = sound_object([[characters_voice\scenario\deadlake\actor\hero_thoughts_phase_20]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_21()
	local snd = sound_object([[characters_voice\scenario\deadlake\actor\hero_thoughts_phase_21]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_22()
	local snd = sound_object([[characters_voice\scenario\deadlake\actor\hero_thoughts_phase_22]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_23()
	local snd = sound_object([[characters_voice\scenario\deadlake\actor\hero_thoughts_phase_23]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_24()
	local snd = sound_object([[characters_voice\scenario\deadlake\actor\hero_thoughts_phase_24]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_25()
	local snd = sound_object([[characters_voice\scenario\deadlake\actor\hero_thoughts_phase_25]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_26()
	local snd = sound_object([[characters_voice\scenario\deadlake\actor\hero_thoughts_phase_26]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_27()
	local snd = sound_object([[characters_voice\scenario\deadlake\actor\hero_thoughts_phase_27]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_28()
	local snd = sound_object([[characters_voice\scenario\deadlake\actor\hero_thoughts_phase_28]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_29()
	local snd = sound_object([[characters_voice\scenario\deadlake\actor\hero_thoughts_phase_29]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_30()
	local snd = sound_object([[characters_voice\scenario\deadlake\actor\hero_thoughts_phase_30]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_31()
	local snd = sound_object([[characters_voice\scenario\deadlake\actor\hero_thoughts_phase_31]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_32()
	local snd = sound_object([[characters_voice\scenario\deadlake\actor\hero_thoughts_phase_32]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.hero_thoughts_33()
	local snd = sound_object([[characters_voice\scenario\deadlake\actor\hero_thoughts_phase_33]])
     snd:play_no_feedback(db.actor,sound_object.s2d, 0, vector(), 1.0, 1.0)
end

function xr_effects.wiz_scaner_destroy(actor, npc)
	if xr_conditions.actor_in_zone(actor, npc, {"wiz_anom_scaner_logic"})
		and not has_alife_info("wiz_scaner_destroy_info") then
		db.actor:give_info_portion("wiz_scaner_destroy_info")
        xr_effects.remove_item(actor, npc, {"wiz_scanner_device"})		
		xr_effects.spawn_object(actor, nil, {"jup_b32_ph_scanner","wiz_scanner_place"})
	end	
end

function xr_effects.wiz_spawn_krovosos()
xr_effects.spawn_object(actor, nil, {"bloodsucker_boloto","wiz_sp_bloodshacker_boloto_foma", "0","0"})
end

function xr_effects.wiz_die_m24_searching(actor, npc)
	if xr_conditions.actor_in_zone(actor, npc, {"wiz_dead_mi24_sr"})	then
		db.actor:give_info_portion("wiz_die_m24_searching")
	end
end

function xr_effects.wiz_climb_over_the_fence(actor, npc)
	if xr_conditions.actor_in_zone(actor, npc, {"wiz_uninvited_guests_cover_sr"})	then
		db.actor:give_info_portion("wiz_climb_over_the_fence")
	end
end

function xr_effects.berserk_particle_play(actor, npc)
if npc:clsid() == clsid.chimera_s then bone = "head_boss"	-- для химер;
elseif npc:clsid() == clsid.burer_s then bone = "head"
elseif npc:clsid() ~= clsid.chimera_s and npc:clsid() ~= clsid.burer_s then bone = "bip01_head"
end
	npc:start_particles("anomaly2\\bold_idle_sarkofag", bone)
end

function xr_effects.berserk_particle_stop(actor, npc)
local bone1 = "bip01_head"
local bone2 = "bip01_spine1"
	npc:stop_particles("anomaly2\\bold_idle_sarkofag", bone1)
end

function xr_effects.relocate_really_all_actor_inventory_to_box(actor, npc, p)
	local function transfer_object_item(item)
		if item:section() ~= "bolt" and item:section() ~= "device_torch" then
			db.actor:transfer_item(item, inv_box_1)
		end
	end
	inv_box_1 = get_story_object (p[1])
	actor:inventory_for_each(transfer_object_item)
end

function xr_effects.show_path(actor, npc, p)
local hud = get_hud():AddCustomStatic("style_path", true)
hud:wnd():TextControl():SetTextST(game.translate_string(p[1]))
hud.m_endTime = time_global()/1000+70
end

function xr_effects.show_path_name(actor, npc, p)
local hud = get_hud():AddCustomStatic("style_path_name", true)
hud:wnd():TextControl():SetTextST(game.translate_string(p[1]))
hud.m_endTime = time_global()/1000+70
end

function xr_effects.show_path_descr(actor, npc, p)
local hud = get_hud():AddCustomStatic("style_path_descr", true)
hud:wnd():TextControl():SetTextST(game.translate_string(p[1]))
hud.m_endTime = time_global()/1000+70
end

function xr_effects.del_show_path_123(actor, npc, p)
	local hud = get_hud()
	cs_text = hud:GetCustomStatic("style_path")
	cs_text = hud:GetCustomStatic("style_path_name")
	cs_text = hud:GetCustomStatic("style_path_descr")
	if cs_text then
		hud:RemoveCustomStatic("style_path")
		hud:RemoveCustomStatic("style_path_name")
		hud:RemoveCustomStatic("style_path_descr")
	end
end

function xr_effects.agro_start_cs_callback_1() 
xr_effects.disable_ui(db.actor, nil)
level.add_cam_effector("camera_effects\\cs_actor_contract.anm", 29, false, "")
level.add_cam_effector("camera_effects\\scenario_cam\\lake\\actor_wakeup_bandits_base.anm", 3457, false, "xr_effects.agro_start_cs_callback_5_the_is_done")
level.add_pp_effector("thermal.ppe",1727,true)
--level.add_pp_effector("hard_punch_actor.ppe",8814,true)
end

function xr_effects.agro_start_cs_callback_5_the_is_done()
xr_effects.enable_ui(db.actor, nil)
level.remove_pp_effector(1727)
level.remove_pp_effector(8814)
db.actor:activate_slot(3)
end
