
--[[
	2023.11.09
	Banjaji's Crafting system improvements v4.0
	* One function to rule them all! This script's get_recipes() and get_recipe_tabs() functions are accessed by everything else, so no more duplicate code. 
	* This function is accessed by ui_workshop.script, item_recipe.script and ui_pda_encyclopedia_tab.script
	* Script name starts with "aa", so it would be loaded as one of the first
	* The output can be read from all_recipes and all_recipe_tabs variables
	* Brought default_recipe_notes from ui_workshop.script and made it global
	* Wrote the code to be highly monkeypatchable
	v4.1
	* Added init() and sent new callback recipes_reload_start
	
	Old recipe format: a_craftable_item = toolkit_number, recipe, component1, component1_amount,  component2, component2_amount...
	New recipe format: a_recipe_id_item = result_item1, result_item1_amount, result_item2, result_item2_amount... \ recipe_note1, recipe_note2... \ tool1, tool1_amount, tool2, tool2_amount... \ component1, component1_amount, component2, component2_amount...

--]]


-------------------------------------------------------------------
-- Global constants
-------------------------------------------------------------------

-- Default notes that don't actually exist as items
default_recipe_notes = {
	"recipe_basic_0",
	"recipe_advanced_0",
	"recipe_expert_0",
	"recipe_drug_0",
	"recipe_ammo_0"
}


--[[ Comment
Output: recipes_table[recipe_tab_index][recipe_index_in_tab] = {
	["identificator"] = item_section
	["results"] = {[result_section1] = amount_needed, [result_section2] = amount_needed...}, 
	["notes"] = {[note_section1] = 1, [note_section2] = 1...},
	["tools"] = {[tool_section1] = amount_needed, [tool_section2] = amount_needed...}, 
	["components"] = {[component_section1] = amount_needed, [component_section2] = amount_needed...}
}

Example (8 and 12 are random numbers for the example)
self.recipe_tabs[8] = "st_ui_craft_medical"
self.recipes[8][12]["identificator"] = "yadylin"
self.recipes[8][12]["results"]["yadylin"] = 1
self.recipes[8][12]["notes"]["recipe_drug_1"] = 1
self.recipes[8][12]["tools"]["itm_drugkit"] = 1
self.recipes[8][12]["components"]["drug_sleepingpills"] = 3
self.recipes[8][12]["components"]["protein"] = 1
self.recipes[8][12]["jar"]["protein"] = 1
--]]
-- These are global for modders to access. Initializes only once, unless someone calls LoadRecipesLTX() again
all_recipes = nil -- recipes
all_recipe_tabs = nil -- recipe tab titles

-- These are not MCM variables to give modder more freedom over recipes. Otherwise player will override recipe component amounts with these values
crafting_achievement_bonus = 1 -- you need this many components less after the achievement
min_components_for_bonus = 5 -- the bonus applies only if you need this many components in the first place

-------------------------------------------------------------------
-- Functions
-------------------------------------------------------------------

-- Gets recipes. See the example in comment above all_recipes
function get_recipes()
	init() -- initialize tables if necessary
	return all_recipes
end

-- Returns all recipe tabs table. Inits the table if necessary
-- Output: recipe_tab_titles[recipe_tab_index] = title
function get_recipe_tabs()
	init() -- initialize tables if necessary
	return all_recipe_tabs
end

-- Initializes the tables if necessary.
function init()
	if (not all_recipes) or (not all_recipe_tabs) then -- one of the main tables is nil
		LoadRecipesLTX() -- Load recipes into memory
	end 
end

-- Sets the recipe tables. Not necessary, since the variables are global
function set_recipes(recipes)
	all_recipes = recipes
end
function set_recipe_tabs(tabs)
	all_recipe_tabs = tabs
end

-- Old recipe format: a_craftable_item = toolkit_number, recipe, component1, component1_amount,  component2, component2_amount...
-- New recipe format: a_recipe_id_item = result_item1, result_item1_amount, result_item2, result_item2_amount... \ recipe_note1, recipe_note2... \ tool1, tool1_amount, tool2, tool2_amount... \ component1, component1_amount, component2, component2_amount...


-- Load recipes into memory, gives already formated and corrected amounts for crafting. Required amounts (e.g. components) are integers (minimum 1) of uses.
-- Results are float (condition, minimum 0) for normal items and integer of uses for multiuse items and ammo (minimum 1).
function LoadRecipesLTX()
	-- Send callback that initialization started
	SendScriptCallback("recipes_reload_start", all_recipes, all_recipe_tabs)
	
	local recipes = {}
	local recipe_tabs = {}
	local tab_index = 1 -- recipe tab (section) index
	local section_finder = -10000 --  Now instead of checking for recipe sections as subsequent integers the code checks integers from -10000 to 10000. If your section number is somewhere in between you can have any integer (not necessarily subsequent).
	local ini = itms_manager.ini_craft
	
	-- Check for recipe tabs
	while section_finder <= 10000 do
		local tab_string = "craft_"..tostring(section_finder)
		if ini:section_exist(tab_string) then
			
			-- Check for recipe lines
			local n = ini:line_count(tab_string) or 0
			recipes[tab_index] = {} 
			local title
			
			-- Iterate over all recipes under that tab
			local recipe_index = 1
			for i=0, n-1 do
				local result, id, value = ini:r_line(tab_string , i , "", "") -- section name, line index, default value, value type
				
				-- Function to help monkeypatching. You can overwrite the content of this
				result, id, value = intercept_LoadRecipesLTX1(result, id, value)
				
				local recipe = string_to_recipe(id, value, true, true)
				
				-- Function to help monkeypatching. You can overwrite the content of this
				recipe = intercept_LoadRecipesLTX2(recipe)
				
				-- Some error
				if not recipe then
					goto continue_loadline -- skip this loop
				end
				
				-- The line had title and recipe returned the string
				if type(recipe) == "string" then
					title = recipe
					goto continue_loadline -- skip this loop
				end
				
				recipes[tab_index][recipe_index] = recipe
				recipe_index = recipe_index + 1 -- increment recipe_index
				
				::continue_loadline:: -- continue loop with goto
			end
			
			-- Add tab title to recipe_tabs
			title = title or "Undefined"
			recipe_tabs[tab_index] = title
			
			tab_index = tab_index + 1
		end
		section_finder = section_finder + 1
	end
	
	-- Iterate over tabs and check if tab has recipes. If not then delete the tab
	recipes, recipe_tabs = check_empty_tabs(recipes, recipe_tabs)
	
	-- Function to help monkeypatching. You can overwrite the content of this
	recipes, recipe_tabs = intercept_LoadRecipesLTX3(recipes, recipe_tabs)
	
	-- output amounts have to be integers except for results which may be floats
	all_recipes = recipes
	all_recipe_tabs = recipe_tabs
	--utils_data.print_table(all_recipe_tabs)
	--utils_data.print_table(all_recipes)
	
	-- Send callback that the tables have been (re)initialized
	SendScriptCallback("recipes_reloaded", all_recipes, all_recipe_tabs)
end

-- Takes a string (usually from LTX) and converts it to recipe table. Empty line returns nil, not a table
function string_to_recipe(id, value, cut_characters, consider_achievement, default_item, separator)
	
	-- Empty line
	if (not id) or (not value) or (id == "") or (value == "") then
		return -- skip this loop
	end
	
	-- If it's title line then return recipe tab title
	if (id == "title") then
		return value
	end
	
	-- Remove recipe identificator first 2 characters
	if cut_characters then
		id = string.sub(id,3)
	end
	
	-- If item doesn't exist, use unused item sigaret_for_nps (bug icon)
	id = check_id(id, default_item)
	
	-- remove whitespaces just in case
	value = string.gsub(value, "%s+", "")
	
	local is_vanilla = is_vanilla_recipe(value)
	if (is_vanilla == nil) then
		printe("! aa_load_recipes_Banjaji_CSI.string_to_recipe() | Invalid recipe. Skipping. Tab: [%s], id: [%s]",tab_string, tostring(id)) 
		return -- skip this loop
	elseif is_vanilla then
		value = reformat_vanilla_recipe_string(id, value)
	end
	
	-- separate recipe note, output, tools and components
	local sep = separator or "\\"
	local categories = str_explode(value, sep) -- one backward slash, the second one is for LUA string handling
	
	-- get tables with items and amounts and compile tables into one master-table
	local recipe = {}
	recipe.identificator = id
	recipe.results = get_item_pairs(categories[1])
	recipe.notes = get_item_pairs(categories[2])
	recipe.tools = get_item_pairs(categories[3])
	recipe.components = get_item_pairs(categories[4])
	
	-- Correct recipe
	recipe = correct_string_recipe(recipe, consider_achievement)
	
	return recipe
end

-- If id item doesn't exist, use unused item sigaret_for_nps (bug icon)
function check_id(id, default_item)
	if not(id and ini_sys:section_exist(id)) then -- and (id ~= "tle")
		printe("! aa_load_recipes_Banjaji_CSI.check_id() | section [%s] not found! Using default item.",id)
		id = default_item or "sigaret_for_nps"
	end
	return id
end

-- Checks what format the recipe is in. This is for backwards compatibility.
-- This check can't reliably distinguish v3.x and v4.x recipes without restricting v4.x features, so few errors might not be caught
function is_vanilla_recipe(str)
	-- Separates string by comma
	local list = str_explode(str,",")
	
	-- in vanilla format the first value is toolkit number but it might also be so in CSI v3.x
	-- in v4.x first content has to be string
	if tonumber(list[1]) then -- if it's number
		
		-- check if it is CSI v3.x
		if (((#list) % 2) ~= 0) or -- list length is odd or
		(list[1] == "") or (list[2] == "") or (list[3] == "") or (list[4] == "") or -- one of the first fields has nothing or
		(not list[1]) or (not list[2]) or (not list[3]) or (not list[4]) then -- one of the first fields has nothing
		
			printe("! aa_load_recipes_Banjaji_CSI.is_vanilla_recipe() | recipe is from CSI v3.x. You need to update the recipe. The string: [%s]",str) 
			return -- return nil for error handling
		end
		
		-- must be vanilla format
		return true 
	end
	return false
end

-- Takes vanilla recipe format and converts it into new format
-- Old recipe format: a_craftable_item = toolkit_number, recipe, component1, component1_amount,  component2, component2_amount...
-- New recipe format: a_recipe_id_item = result_item1, result_item1_amount, result_item2, result_item2_amount... \ recipe_note1, recipe_note2... \ tool1, tool1_amount, tool2, tool2_amount... \ component1, component1_amount, component2, component2_amount...
function reformat_vanilla_recipe_string(id, value)
	if not value then return end
	
	-- If item doesn't exist, use unused item sigaret_for_nps (bug icon)
	id = check_id(id, default_item)
	
	-- Separates string by comma
	local list = str_explode(value,",")
	
	-- Tool index and recipe section
	local toolnr = tonumber(list[1]) or 1
	local tool = ui_workshop.workshop_toolkits[toolnr]
	local note = list[2]
	
	if (not tool) or (not note) then -- Print error and prevent crash. Otherwise users blame me for bad recipes
		printe("! aa_load_recipes_Banjaji_CSI.reformat_vanilla_recipe_string() | Not my fault, bad recipe! | Recipe id [%s]: tool section [%s] or note section [%s] not found!", id, tool, note)
		printe("! Original string: [%s]", value)
		return "" -- return empty string (empty recipe)
	end
	
	-- id is identificator and result
	output_str = id .. "\\" .. note .. "\\" .. tool .. "\\" -- no need for amount since it defaults to 1
	
	-- Iterates over components by registering its section and then the required amount
	local section_index = 3 -- goes 3,5,7,9 to read component section
	while list[section_index] and tonumber(list[section_index + 1]) do -- component and it's numerical amount exists.
		local name = tostring(list[section_index]) -- item name
		local amt = tostring(list[section_index + 1]) -- amount needed
		
		if ini_sys:section_exist(name) then -- component section is correct
			-- box to bullet conversion, vanilla used full boxes
			if IsItem("ammo",name) then
				local max_uses = IsItem("ammo",name)
				amt = amt * max_uses
			end
			
			if section_index == 3 then -- first component
				output_str = output_str .. name .. "," .. amt
			else
				output_str = output_str .. "," .. name .. "," .. amt
			end
			
		else
			printe("! aa_load_recipes_Banjaji_CSI.reformat_vanilla_recipe_string() | component section [%s] not found for [%s] recipe!", name, id)
		end
		
		section_index = section_index + 2
	end
	
	return output_str
end

-- Iterates over items by registering its section and then the required amount
function get_item_pairs(str, separator, default_amt)
	-- Check for empty or missing category
	if (not str) or (str == "") then
		return {}
	end
	
	-- Separates item and amount
	local sep = separator or ","
	local list = str_explode(str,sep)
	
	-- invalid string, has no content
	if (#list == 0) or ((#list == 1) and (list[1] == "")) then
		return {}
	end
	
	
	-- Iterate over all things in list
	local output_tbl = {}
	local list_index = 1
	while (list_index <= #list) do
		output_tbl, list, list_index = get_item_pairs_iter(output_tbl, list, list_index, default_amt) -- separate function to ease monkeypatching
	end
	
	return output_tbl
end

-- Get item section and corresponding amount and write them to output table
function get_item_pairs_iter(output_tbl, list, list_index, default_amt)
	local item = list[list_index]
	local amount = default_amt or 1 -- default to 1
	
	if (not tonumber(item)) then -- consider sections, not amounts
		if ini_sys:section_exist(tostring(item)) or is_in_table(aa_load_recipes_Banjaji_CSI.default_recipe_notes, item) then -- isn't amount number and component section is correct
	
			-- If item section is followed by number then save that as the amount
			local amt_check = tonumber(list[list_index + 1]) -- last one returns nil if larger than list
			if amt_check then
				amount = amt_check
			end
			
			-- check for multiple entries of same item and if true, add together amounts
			if is_in_table_keys(output_tbl, item) then
				amount = amount + output_tbl[item]
			end
			
			-- save section and amount to output table
			output_tbl[item] = amount -- passed table is modified directly
		else
			printe("! aa_load_recipes_Banjaji_CSI.get_item_pairs() | component section [%s] not found!", tostring(item))
		end
	end
	
	list_index = list_index + 1 -- checks amount twice but I don't care because it's ignored anyways
	return output_tbl, list, list_index
end

-- Run corrections on read recipe
function correct_string_recipe(recipe, consider_achievement)
	-- round and clip amounts
	recipe = amount_correction(recipe)
	
	-- Consider achievements component reduction
	if consider_achievement then
		recipe.components = achievement_reduction(recipe.components)
	end
	
	-- Remove non-note items from notes table
	recipe.notes = correct_notes(recipe.notes)
	
	-- Check if recipe has any items. If not then pass nil to ignore the recipe
	recipe = check_empty_recipe(recipe)
	
	return recipe
end

-- Corrects read amounts. For components, tools and recipes it's rounded down to integer and minimum is 1. 
-- For results the minimum is 0 condition for normal items. 
-- For results when dealing with ammo or multiuse items round uses to round(amount * max_uses), minimum is 1 use. 
function amount_correction(recipe)
	
	-- Iterate over categories
	for category, items in pairs(recipe) do
		if category ~= "identificator" then -- ignore identificator key
			recipe[category] = {}
			
			-- Iterate over items
			for item_sec, amount in pairs(items) do
				local amt
				if (category == "results") then -- results
					amt = amount_correction_result(item_sec,amount) -- Output amount is in integer uses, minimum 1
				else -- e.g. components
					amt = amount_correction_other(item_sec,amount) -- round down but minimum 1
				end
				
				recipe[category][item_sec] = amt -- save corrected amount
			end
		end
	end
	
	return recipe
end

-- Output amount is in integer uses, minimum 1
function amount_correction_result(item_sec,amount)
	local amt
	if IsItem("ammo",item_sec) or IsItem("multiuse",item_sec) then -- ammo box or multiuse item
		local max_uses = 1
		
		-- Find max item uses (multiuse item or ammo box ammo count)
		if IsItem("ammo",item_sec) then -- ammo box
			max_uses = IsItem("ammo",item_sec) or 1
		elseif IsItem("multiuse",item_sec) then -- multi-use item
			max_uses = ini_sys:r_float_ex(item_sec,"max_uses") or 1
		end
		
		-- Round resulting uses to nearest integer (fraction support) and minimum amount is 1
		amt = math.max(round(amount * max_uses),1)
		
	else -- normal item
		amt = math.max(amount, 0) -- minimum 0 condition
	end
	
	return amt
end

-- round down but minimum 1
function amount_correction_other(item_sec,amount)
	return math.max(math.floor(amount), 1) 
end

-- Consider achievements component reduction
function achievement_reduction(components)
	if game_achievements.has_achievement("artificer_eagerness") then
		for key,value in pairs(components) do
			if (value >= min_components_for_bonus) then
				local amt = math.max(value - crafting_achievement_bonus, 1) -- minimum 1 component required
				components[key] = amt
			end
		end
	end
	return components
end

-- Remove non-notes from notes table
function correct_notes(note_table)
	for note_sec,amount in pairs(note_table) do
		if (not is_note(note_sec)) then
			note_table[note_sec] = nil
		end
	end
	
	return note_table
end

-- Return whether the item is a note
function is_note(item_sec)
	return (SYS_GetParam(0, item_sec, "kind") == "i_letter") -- all vanilla notes have kind = i_letter
end

-- Check if recipe has any items. If not then pass nil to ignore the recipe
function check_empty_recipe(recipe)
	if (tableLength(recipe.results) <= 0) and (tableLength(recipe.tools) <= 0) and (tableLength(recipe.components) <= 0) then -- if no items exist besides notes
		recipe = nil -- pass nil to ignore the recipe
	end
	return recipe
end

-- Iterate over tabs and check if tab has recipes. If not then delete the tab
function check_empty_tabs(recipes, recipe_tabs)
	for tab_index, recipe_tab in ipairs(recipes) do -- Iterate over recipe tabs
		if tableLength(recipe_tab) == 0 then -- no recipes
			table.remove(recipes, tab_index)
			table.remove(recipe_tabs, tab_index)
		end
	end
	return recipes, recipe_tabs
end


-- Functions to help monkeypatching. You can overwrite the content of this
function intercept_LoadRecipesLTX1(result, id, value)
	return result, id, value
end
function intercept_LoadRecipesLTX2(recipe)
	return recipe
end
function intercept_LoadRecipesLTX3(recipes, recipe_tabs)
	return recipes, recipe_tabs
end

-------------------------------------------------------------------
-- Callbacks
-------------------------------------------------------------------

-- Callback that processes achievements. It's monkeypatchable in order to add new achievements
function actor_on_achievement_earned(achievement, message)
	artificer_eagerness_gained(achievement, message)
end

-- Process all_recipes and consider achievements component reduction 
function artificer_eagerness_gained(achievement, message)
	if achievement and (achievement == "artificer_eagerness") then
		init() -- initialize tables if necessary
		for tab_index, recipe_tab in ipairs(all_recipes) do -- Iterate over recipe tabs
			for recipe_index, recipe in ipairs(recipe_tab) do -- Iterate over recipes
				all_recipes[tab_index][recipe_index]["components"] = achievement_reduction(recipe.components)
			end
		end
	end
end

-- Registers callbacks
function on_game_start()
	AddScriptCallback("recipes_reload_start")
	AddScriptCallback("recipes_reloaded")
	RegisterScriptCallback("actor_on_achievement_earned", actor_on_achievement_earned)
end


-------------------------------------------------------------------
-- Functions to help adding recipes through scripts. Some ideas come from workshop_autoinject. Not tested
-------------------------------------------------------------------
-- You can use these functions or otherwise directly modify the global constants.
-- E.g. empty_table(all_recipes) removes all recipes or all_recipes[2][5] = recipe changes a recipe. You need to also consider all_recipe_tabs


-----------------------
-- Tab operations
-----------------------
-- Add new recipe tab with recipes
function add_new_recipe_tab(tab_index, recipes, tab_name)
	init() -- initialize tables if necessary
	tab_index = Correct_tab_index(tab_index) -- Correct tab_index or find index from string
	table.insert(all_recipes, tab_index, recipes or {}) 
	table.insert(all_recipe_tabs, tab_index, tab_name or "Undefined")
end

-- Remove recipe tab
function remove_recipe_tab(tab_index)
	init() -- initialize tables if necessary
	tab_index = Correct_tab_index(tab_index) -- Correct tab_index or find index from string
	table.remove(all_recipes, tab_index) 
	table.remove(all_recipe_tabs, tab_index)
end

-- Get the index of tab with provided string as the title
function get_tab_index(title_variable_str)
	init() -- initialize tables if necessary
	for tab_index, tab_title in ipairs(all_recipe_tabs) do
		if (title_variable_str == tab_title) then
			return tab_index
		end
	end
end


-----------------------
-- Recipe adding
-----------------------

-- Add new recipe to tab
function add_new_recipe(tab_index, recipe)
	if not recipe then return end
	init() -- initialize tables if necessary
	tab_index = Correct_tab_index(tab_index) -- Correct tab_index or find index from string
	
	-- Init tab if necessary
	if (not all_recipes[tab_index]) then 
		add_new_recipe_tab(tab_index)
	end
	table.insert(all_recipes[tab_index], recipe)
	
	return tab_index, #(all_recipes[tab_index]) -- return tab and recipe index for easy checking/processing
end

-- Add new recipe from string to some tab
function add_new_recipe_str(tab_index, id, recipe_string, cut_characters, consider_achievement, default_item, separator)
	init() -- initialize tables if necessary
	tab_index = Correct_tab_index(tab_index) -- Correct tab_index or find index from string
	
	-- assume ltx format
	if not id then 
		recipe_string = string.gsub(recipe_string, "%s+", "") -- remove whitespaces just in case
		local exploded = str_explode(recipe_string,"=") -- list from string
		if (#exploded > 1) then -- normal recipe, otherwise id stays nil and recipe_string stays the same
			id = exploded[1] -- get left side of the equation 
			recipe_string = exploded[2] -- get right side of the equation
		end
	end
	
	-- Convert string to recipe table
	local recipe = string_to_recipe(id, recipe_string, cut_characters, consider_achievement, default_item, separator)
	if (not recipe) or (type(recipe) ~= "table") then return end -- Invalid/empty recipe. Don't save
	
	return add_new_recipe(tab_index, recipe) -- add recipe and return tab and recipe index for easy checking/processing
end

-----------------------
-- Recipe overwriting operations
-----------------------

-- Specify a crafting recipe that will change all other recipes with the identificator in a specific tab or everywhere.
function override_recipe_by_id(identificator, recipe, tab_index)
	init() -- initialize tables if necessary
	
	if tab_index then -- delete from specific tab
		tab_index = Correct_tab_index(tab_index) -- fit bad index into bounds
		
		for recipe_index, rcp in ipairs(all_recipes[tab_index]) do -- Iterate over recipes in the tab
			if rcp.identificator == identificator then
				all_recipes[tab_index][recipe_index] = recipe
			end
		end
	
	else -- override everywhere
		for tab_index, tab_recipes in ipairs(all_recipes) do -- Iterate over recipe tabs
			for recipe_index, rcp in ipairs(tab_recipes) do -- Iterate over recipes in the tab
				if rcp.identificator == identificator then
					all_recipes[tab_index][recipe_index] = recipe
				end
			end
		end
	end
end

-----------------------
-- Recipe deleting operations
-----------------------

-- Delete recipes with the specified identificator from specific tab or from everywhere
function delete_recipes_by_id(identificator, tab_index)
	init() -- initialize tables if necessary
	
	if tab_index then -- delete from specific tab
		tab_index = Correct_tab_index(tab_index) -- fit bad index into bounds
		
		for recipe_index, recipe in ipairs(all_recipes[tab_index]) do -- Iterate over recipes in the tab
			if recipe.identificator == identificator then
				all_recipes[tab_index][recipe_index] = nil -- writes recipe as nil
			end
		end
	
	else -- delete from everywhere
		override_recipe_by_id(identificator, nil) -- writes recipe as nil
	end
end

-----------------------
-- List collection operations
-----------------------

-- Collect recipes that that require/give certain item
function collect_note_recipes(recipes, item_section) -- notes
	return collect_item_recipes(recipes, item_section, "notes")
end
function collect_comp_recipes(recipes, item_section) -- components
	return collect_item_recipes(recipes, item_section, "components")
end
function collect_result_recipes(recipes, item_section) -- results
	return collect_item_recipes(recipes, item_section, "results")
end
function collect_tool_recipes(recipes, item_section) -- tools
	return collect_item_recipes(recipes, item_section, "tools")
end
function collect_id_recipes(recipes, id_section) -- identificators
	local gathered_recipes = {}
	for _, recipe_tab in ipairs(recipes) do -- Iterate over recipe tabs
		for _, recipe in ipairs(recipe_tab) do -- Iterate over recipes
			if (recipe["identificator"] == id_section) then -- this identificator is used by this recipe
				table.insert(gathered_recipes, recipe)
			end
		end
	end
	return gathered_recipes
end

-- Collect recipes that that have section in category
function collect_item_recipes(recipes, item_section, category)
	local gathered_recipes = {}
	
	for _, recipe_tab in ipairs(recipes) do -- Iterate over recipe tabs
		for _, recipe in ipairs(recipe_tab) do -- Iterate over recipes
			for sec, _ in pairs(recipe[category]) do -- Iterate over required/gained items
				if (sec == item_section) and (not is_in_table(gathered_recipes, recipe)) then -- item is required/gained with this recipe and recipe isn't already in table
					table.insert(gathered_recipes, recipe)
				end
			end
		end
	end
	
	return gathered_recipes
end

-----------------------
-- Technical operations
-----------------------

-- Iterate over all recipes and run the defined function at every recipe level
function iterate_func_recipes(funct_recipe, recipes_table)
	for tab_index, recipe_tab in ipairs(recipes_table) do -- Iterate over recipe tabs
		for recipe_index, recipe in ipairs(recipe_tab) do -- Iterate over recipes
			funct_recipe(recipes_table, tab_index, recipe_index) -- run the passed function
		end
	end
end

-- Iterate over the entire table and run the defined function at every item level (or identificator)
function iterate_func_items(funct, recipes_table)
	for tab_index, recipe_tab in ipairs(recipes_table) do -- Iterate over recipe tabs
		for recipe_index, recipe in ipairs(recipe_tab) do -- Iterate over recipes
			for category, items in pairs(recipe) do -- Iterate over categories: results, tools, components, notes, identificator in random order
				if category == "identificator" then
					funct(recipes_table, tab_index, recipe_index, category) -- run the passed function
				else
					for item, amount in pairs(items) do -- Iterate over required/gained items
						funct(recipes_table, tab_index, recipe_index, category, item) -- run the passed function
					end
				end
			end
		end
	end
end

-----------------------
-- Utility but still core operations
-----------------------

-- Correct tab_index number to fit into bounds
function Correct_tab_index(tab_index)
	local table_len = tableLength(all_recipe_tabs)
	
	if type(tab_index) == "number" then -- number correction, by default index remains the same
		if tab_index > table_len then -- index accesses element after list
			tab_index = table_len + 1 -- defaults to end of the table
		elseif tab_index < 1 then -- index is below LUA default iterator range
			tab_index = 1 -- limit to 1
		end
	elseif type(tab_index) == "string" then -- find the tab index by title
		tab_index = get_tab_index(tab_index) or 1
	else
		tab_index = table_len + 1 -- defaults to end of the table
	end
	return tab_index
end

-------------------------------------------------------------------
-- Utility functions
-------------------------------------------------------------------

-- Iterate over table keys and if section is in keys return true
function is_in_table_keys(table, section)
	for key, _ in pairs(table) do
		if (section == key) then
			return true
		end
	end
	return false
end
-- Iterate over table values and if section is in values return true
function is_in_table(table, section)
	for _, value in pairs(table) do
		if (section == value) then
			return true
		end
	end
	return false
end

-- Gets table length
function tableLength(table)
	local count = 0
	if type(table) == "table" then
		for _ in pairs(table) do count = count + 1 end
	end
	return count
end
